import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import pkg, { type Pool as PoolType } from 'pg';
import { PostgreSQLServer, allTools, type RuntimeConfig } from '../index';
import { DatabaseConnection } from '../utils/connection';

const { Pool } = pkg;
const integrationConnectionString = process.env.POSTGRES_MCP_INTEGRATION_CONNECTION_STRING;
const describePostgres = integrationConnectionString ? describe : describe.skip;

function getIntegrationConnectionString(): string {
  if (!integrationConnectionString) {
    throw new Error('POSTGRES_MCP_INTEGRATION_CONNECTION_STRING is required for integration tests.');
  }

  return integrationConnectionString;
}

function runtimeConfig(overrides: Partial<RuntimeConfig> = {}): RuntimeConfig {
  return {
    securityPolicy: { mode: 'readonly', allowDestructive: false },
    allowToolConnectionString: false,
    connectionString: getIntegrationConnectionString(),
    ...overrides
  };
}

function quoteIdent(identifier: string): string {
  return `"${identifier.replace(/"/g, '""')}"`;
}

describePostgres('PostgreSQL integration', () => {
  let setupPool: PoolType;
  let schemaName: string;

  const table = (name: string): string => `${quoteIdent(schemaName)}.${quoteIdent(name)}`;

  beforeAll(async () => {
    schemaName = `mcp_integration_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
    setupPool = new Pool({
      connectionString: getIntegrationConnectionString(),
      allowExitOnIdle: true,
      connectionTimeoutMillis: 2000,
      idleTimeoutMillis: 1000
    });

    await setupPool.query(`CREATE SCHEMA ${quoteIdent(schemaName)}`);
    await setupPool.query(`
      CREATE TABLE ${table('items')} (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        quantity integer NOT NULL
      )
    `);
  });

  beforeEach(async () => {
    vi.spyOn(console, 'error').mockImplementation(() => undefined);
    vi.spyOn(console, 'warn').mockImplementation(() => undefined);
    await setupPool.query(`TRUNCATE ${table('items')} RESTART IDENTITY`);
    await setupPool.query(`DROP TABLE IF EXISTS ${table('sql_created')}`);
    await DatabaseConnection.cleanupPools();
  });

  afterAll(async () => {
    vi.restoreAllMocks();
    await DatabaseConnection.cleanupPools();

    if (setupPool) {
      await setupPool.query(`DROP SCHEMA IF EXISTS ${quoteIdent(schemaName)} CASCADE`);
      await setupPool.end();
    }
  });

  it('executes a readonly query through the MCP server boundary against real PostgreSQL', async () => {
    await setupPool.query(`INSERT INTO ${table('items')} (name, quantity) VALUES ($1, $2)`, ['alpha', 2]);
    const server = new PostgreSQLServer(allTools, runtimeConfig(), { registerSignalHandlers: false });

    try {
      const result = await server.handleToolCall('pg_execute_query', {
        operation: 'select',
        query: `SELECT name, quantity FROM ${table('items')} WHERE quantity >= $1 ORDER BY id`,
        parameters: [1],
        limit: 10
      });
      const text = String(result.content[0].text);

      expect(result.isError).toBeUndefined();
      expect(text).toContain('Query executed successfully. Retrieved 1 rows.');
      expect(text).toContain('"name": "alpha"');
      expect(text).toContain('"quantity": 2');
    } finally {
      await server.close();
    }
  });

  it('blocks write tools in readonly mode before the database is changed', async () => {
    const server = new PostgreSQLServer(allTools, runtimeConfig(), { registerSignalHandlers: false });

    try {
      const result = await server.handleToolCall('pg_execute_mutation', {
        operation: 'insert',
        schema: schemaName,
        table: 'items',
        data: { name: 'blocked', quantity: 1 }
      });
      const rowCount = await setupPool.query<{ count: string }>(`SELECT COUNT(*) AS count FROM ${table('items')}`);

      expect(result.isError).toBe(true);
      expect(String(result.content[0].text)).toContain('Blocked by PostgreSQL MCP security policy');
      expect(rowCount.rows[0]?.count).toBe('0');
    } finally {
      await server.close();
    }
  });

  it('executes structured write mutations in write mode against real PostgreSQL', async () => {
    const server = new PostgreSQLServer(allTools, runtimeConfig({
      securityPolicy: { mode: 'write', allowDestructive: false }
    }), { registerSignalHandlers: false });

    try {
      const insert = await server.handleToolCall('pg_execute_mutation', {
        operation: 'insert',
        schema: schemaName,
        table: 'items',
        data: { name: 'alpha', quantity: 1 },
        returning: ['id', 'name'],
        maxReturningRows: 10
      });
      const update = await server.handleToolCall('pg_execute_mutation', {
        operation: 'update',
        schema: schemaName,
        table: 'items',
        data: { quantity: 3 },
        where: { name: 'alpha' },
        returning: ['name', 'quantity'],
        maxReturningRows: 10
      });
      const rows = await setupPool.query<{ quantity: number }>(
        `SELECT quantity FROM ${table('items')} WHERE name = $1`,
        ['alpha']
      );

      expect(insert.isError).toBeUndefined();
      expect(String(insert.content[0].text)).toContain('INSERT operation completed successfully. Rows affected: 1');
      expect(update.isError).toBeUndefined();
      expect(String(update.content[0].text)).toContain('"quantity": 3');
      expect(rows.rows).toEqual([{ quantity: 3 }]);
    } finally {
      await server.close();
    }
  });

  it('executes multi-statement arbitrary SQL only through unsafe transactional mode', async () => {
    const server = new PostgreSQLServer(allTools, runtimeConfig({
      securityPolicy: { mode: 'unsafe', allowDestructive: true }
    }), { registerSignalHandlers: false });

    try {
      const result = await server.handleToolCall('pg_execute_sql', {
        sql: `
          CREATE TABLE ${table('sql_created')} (id integer PRIMARY KEY, label text NOT NULL);
          INSERT INTO ${table('sql_created')} (id, label) VALUES (1, 'created');
        `,
        expectRows: false,
        transactional: true
      });
      const rows = await setupPool.query<{ label: string }>(`SELECT label FROM ${table('sql_created')} WHERE id = 1`);

      expect(result.isError).toBeUndefined();
      expect(String(result.content[0].text)).toContain('SQL executed successfully in transaction');
      expect(rows.rows).toEqual([{ label: 'created' }]);
    } finally {
      await server.close();
    }
  });
});
